CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Collections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TmdbId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Overview" character varying(2000),
        "PosterPath" character varying(200),
        "BackdropPath" character varying(200),
        CONSTRAINT "PK_Collections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Countries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Iso31661" character varying(2) NOT NULL,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Genres" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TmdbId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Images" (
        "Id" uuid NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "ContentType" character varying(100) NOT NULL,
        "Data" bytea NOT NULL,
        "Size" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Images" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Keywords" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TmdbId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Keywords" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Languages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Iso6391" character varying(2) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "EnglishName" character varying(100),
        CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Movies" (
        "Id" uuid NOT NULL,
        "TmdbId" integer NOT NULL,
        "Title" character varying(500) NOT NULL,
        "OriginalTitle" character varying(500),
        "Overview" character varying(2000),
        "ReleaseDate" timestamp with time zone,
        "Runtime" integer,
        "Budget" numeric(18,2),
        "Revenue" numeric(18,2),
        "PosterPath" character varying(200),
        "BackdropPath" character varying(200),
        "ImdbId" character varying(20),
        "OriginalLanguage" character varying(10),
        "Popularity" double precision,
        "VoteAverage" double precision,
        "VoteCount" integer,
        "Status" character varying(50),
        "Tagline" character varying(500),
        "Homepage" character varying(500),
        "Adult" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        "DeletedBy" uuid,
        CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "People" (
        "Id" uuid NOT NULL,
        "TmdbId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Biography" character varying(5000),
        "Birthday" timestamp with time zone,
        "Deathday" timestamp with time zone,
        "PlaceOfBirth" character varying(200),
        "ProfilePath" character varying(200),
        "Popularity" double precision,
        "Gender" integer,
        "KnownForDepartment" character varying(100),
        "ImdbId" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_People" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "ProductionCompanies" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TmdbId" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "LogoPath" character varying(200),
        "OriginCountry" character varying(10),
        CONSTRAINT "PK_ProductionCompanies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "AppUsers" (
        "Id" uuid NOT NULL,
        "Username" character varying(50) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" integer NOT NULL,
        "ProfileImageId" uuid,
        "BackgroundImageId" uuid,
        "Bio" character varying(500),
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        "DeletedBy" uuid,
        CONSTRAINT "PK_AppUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AppUsers_Images_BackgroundImageId" FOREIGN KEY ("BackgroundImageId") REFERENCES "Images" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_AppUsers_Images_ProfileImageId" FOREIGN KEY ("ProfileImageId") REFERENCES "Images" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieCollections" (
        "MovieId" uuid NOT NULL,
        "CollectionId" integer NOT NULL,
        CONSTRAINT "PK_MovieCollections" PRIMARY KEY ("MovieId", "CollectionId"),
        CONSTRAINT "FK_MovieCollections_Collections_CollectionId" FOREIGN KEY ("CollectionId") REFERENCES "Collections" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieCollections_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieCountries" (
        "MovieId" uuid NOT NULL,
        "CountryId" integer NOT NULL,
        CONSTRAINT "PK_MovieCountries" PRIMARY KEY ("MovieId", "CountryId"),
        CONSTRAINT "FK_MovieCountries_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieCountries_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieGenres" (
        "MovieId" uuid NOT NULL,
        "GenreId" integer NOT NULL,
        CONSTRAINT "PK_MovieGenres" PRIMARY KEY ("MovieId", "GenreId"),
        CONSTRAINT "FK_MovieGenres_Genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES "Genres" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieGenres_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieImages" (
        "Id" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "FilePath" character varying(200) NOT NULL,
        "ImageType" character varying(50),
        "Language" character varying(10),
        "VoteAverage" double precision,
        "VoteCount" integer,
        "Width" integer,
        "Height" integer,
        CONSTRAINT "PK_MovieImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieImages_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieKeywords" (
        "MovieId" uuid NOT NULL,
        "KeywordId" integer NOT NULL,
        CONSTRAINT "PK_MovieKeywords" PRIMARY KEY ("MovieId", "KeywordId"),
        CONSTRAINT "FK_MovieKeywords_Keywords_KeywordId" FOREIGN KEY ("KeywordId") REFERENCES "Keywords" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieKeywords_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieLanguages" (
        "MovieId" uuid NOT NULL,
        "LanguageId" integer NOT NULL,
        CONSTRAINT "PK_MovieLanguages" PRIMARY KEY ("MovieId", "LanguageId"),
        CONSTRAINT "FK_MovieLanguages_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieLanguages_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieVideos" (
        "Id" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "VideoKey" character varying(50) NOT NULL,
        "Name" character varying(200),
        "Site" character varying(50),
        "Type" character varying(50),
        "Official" boolean NOT NULL,
        CONSTRAINT "PK_MovieVideos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieVideos_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieCast" (
        "Id" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "PersonId" uuid NOT NULL,
        "Character" character varying(500),
        "CastOrder" integer,
        CONSTRAINT "PK_MovieCast" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieCast_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieCast_People_PersonId" FOREIGN KEY ("PersonId") REFERENCES "People" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieCrew" (
        "Id" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "PersonId" uuid NOT NULL,
        "Job" character varying(200),
        "Department" character varying(200),
        CONSTRAINT "PK_MovieCrew" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieCrew_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieCrew_People_PersonId" FOREIGN KEY ("PersonId") REFERENCES "People" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieProductionCompanies" (
        "MovieId" uuid NOT NULL,
        "ProductionCompanyId" integer NOT NULL,
        CONSTRAINT "PK_MovieProductionCompanies" PRIMARY KEY ("MovieId", "ProductionCompanyId"),
        CONSTRAINT "FK_MovieProductionCompanies_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieProductionCompanies_ProductionCompanies_ProductionComp~" FOREIGN KEY ("ProductionCompanyId") REFERENCES "ProductionCompanies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Blocks" (
        "Id" uuid NOT NULL,
        "BlockerId" uuid NOT NULL,
        "BlockedUserId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Blocks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Blocks_AppUsers_BlockedUserId" FOREIGN KEY ("BlockedUserId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Blocks_AppUsers_BlockerId" FOREIGN KEY ("BlockerId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Comments" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Content" character varying(10000) NOT NULL,
        "CommentableType" integer NOT NULL,
        "CommentableId" uuid NOT NULL,
        "ParentCommentId" uuid,
        "Depth" integer NOT NULL DEFAULT 0,
        "IsEdited" boolean NOT NULL,
        "EditedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Comments_Comments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "Comments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Follows" (
        "Id" uuid NOT NULL,
        "FollowerId" uuid NOT NULL,
        "FollowingId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Follows" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Follows_AppUsers_FollowerId" FOREIGN KEY ("FollowerId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Follows_AppUsers_FollowingId" FOREIGN KEY ("FollowingId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieFavorites" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_MovieFavorites" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieFavorites_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_MovieFavorites_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieLists" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "CoverImageId" uuid,
        "IsPublic" boolean NOT NULL DEFAULT TRUE,
        "IsWatchlist" boolean NOT NULL DEFAULT FALSE,
        "FavoriteCount" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedBy" uuid,
        "UpdatedBy" uuid,
        "DeletedBy" uuid,
        CONSTRAINT "PK_MovieLists" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieLists_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Rates" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "Rating" numeric(3,1) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Rates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Rates_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "Reactions" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "CommentId" uuid NOT NULL,
        "Type" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_Reactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reactions_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reactions_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieListFavorites" (
        "UserId" uuid NOT NULL,
        "MovieListId" uuid NOT NULL,
        "Id" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_MovieListFavorites" PRIMARY KEY ("UserId", "MovieListId"),
        CONSTRAINT "FK_MovieListFavorites_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieListFavorites_MovieLists_MovieListId" FOREIGN KEY ("MovieListId") REFERENCES "MovieLists" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE TABLE "MovieListItems" (
        "Id" uuid NOT NULL,
        "MovieListId" uuid NOT NULL,
        "MovieId" uuid NOT NULL,
        "Order" integer NOT NULL DEFAULT 0,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_MovieListItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovieListItems_MovieLists_MovieListId" FOREIGN KEY ("MovieListId") REFERENCES "MovieLists" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MovieListItems_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES "Movies" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    INSERT INTO "AppUsers" ("Id", "BackgroundImageId", "Bio", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Email", "IsActive", "IsDeleted", "LastLoginAt", "PasswordHash", "ProfileImageId", "Role", "UpdatedAt", "UpdatedBy", "Username")
    VALUES ('11111111-1111-1111-1111-111111111111', NULL, 'Regular user account', TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 'user@cinesocial.com', TRUE, FALSE, NULL, 'vFhI8ifMFh619o3+mMsTEQqchDzmnpU6iBB9hlWD05c=', NULL, 1, NULL, NULL, 'user');
    INSERT INTO "AppUsers" ("Id", "BackgroundImageId", "Bio", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Email", "IsActive", "IsDeleted", "LastLoginAt", "PasswordHash", "ProfileImageId", "Role", "UpdatedAt", "UpdatedBy", "Username")
    VALUES ('22222222-2222-2222-2222-222222222222', NULL, 'Administrator account', TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 'admin@cinesocial.com', TRUE, FALSE, NULL, 'PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=', NULL, 2, NULL, NULL, 'admin');
    INSERT INTO "AppUsers" ("Id", "BackgroundImageId", "Bio", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Email", "IsActive", "IsDeleted", "LastLoginAt", "PasswordHash", "ProfileImageId", "Role", "UpdatedAt", "UpdatedBy", "Username")
    VALUES ('33333333-3333-3333-3333-333333333333', NULL, 'Super User account with full privileges', TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 'superuser@cinesocial.com', TRUE, FALSE, NULL, '/rYp3khIqQneVhhzPPROw2jg/XEQGmxrBc7ifXfXZZA=', NULL, 3, NULL, NULL, 'superuser');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_AppUsers_BackgroundImageId" ON "AppUsers" ("BackgroundImageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AppUsers_Email" ON "AppUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_AppUsers_ProfileImageId" ON "AppUsers" ("ProfileImageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_AppUsers_Username" ON "AppUsers" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Blocks_BlockedUserId" ON "Blocks" ("BlockedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Blocks_BlockerId_BlockedUserId" ON "Blocks" ("BlockerId", "BlockedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Collections_TmdbId" ON "Collections" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Comments_CommentableType_CommentableId" ON "Comments" ("CommentableType", "CommentableId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Comments_CreatedAt" ON "Comments" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Comments_IsDeleted" ON "Comments" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Comments_ParentCommentId" ON "Comments" ("ParentCommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Countries_Iso31661" ON "Countries" ("Iso31661");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Follows_FollowerId_FollowingId" ON "Follows" ("FollowerId", "FollowingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Follows_FollowingId" ON "Follows" ("FollowingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Genres_TmdbId" ON "Genres" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Keywords_TmdbId" ON "Keywords" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Languages_Iso6391" ON "Languages" ("Iso6391");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCast_MovieId" ON "MovieCast" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCast_PersonId" ON "MovieCast" ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCollections_CollectionId" ON "MovieCollections" ("CollectionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCountries_CountryId" ON "MovieCountries" ("CountryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCrew_MovieId" ON "MovieCrew" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieCrew_PersonId" ON "MovieCrew" ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieFavorites_MovieId" ON "MovieFavorites" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_MovieFavorites_UserId_MovieId" ON "MovieFavorites" ("UserId", "MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieGenres_GenreId" ON "MovieGenres" ("GenreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieImages_MovieId" ON "MovieImages" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieKeywords_KeywordId" ON "MovieKeywords" ("KeywordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieKeywords_MovieId" ON "MovieKeywords" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieLanguages_LanguageId" ON "MovieLanguages" ("LanguageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieListFavorites_MovieListId" ON "MovieListFavorites" ("MovieListId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieListFavorites_UserId" ON "MovieListFavorites" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieListItems_MovieId" ON "MovieListItems" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_MovieListItems_MovieListId_MovieId_Unique" ON "MovieListItems" ("MovieListId", "MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieListItems_MovieListId_Order" ON "MovieListItems" ("MovieListId", "Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieLists_IsPublic" ON "MovieLists" ("IsPublic");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieLists_UserId" ON "MovieLists" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieLists_UserId_IsWatchlist" ON "MovieLists" ("UserId", "IsWatchlist");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieProductionCompanies_ProductionCompanyId" ON "MovieProductionCompanies" ("ProductionCompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Movies_Popularity" ON "Movies" ("Popularity");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Movies_ReleaseDate" ON "Movies" ("ReleaseDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Movies_TmdbId" ON "Movies" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Movies_VoteAverage" ON "Movies" ("VoteAverage");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_MovieVideos_MovieId" ON "MovieVideos" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_People_Name" ON "People" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_People_TmdbId" ON "People" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProductionCompanies_TmdbId" ON "ProductionCompanies" ("TmdbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Rates_MovieId" ON "Rates" ("MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Rates_UserId_MovieId" ON "Rates" ("UserId", "MovieId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE INDEX "IX_Reactions_CommentId" ON "Reactions" ("CommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reactions_UserId_CommentId" ON "Reactions" ("UserId", "CommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251106185202_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251106185202_InitialCreate', '9.0.10');
    END IF;
END $EF$;
COMMIT;

